### ISSUE TITLE
Getting this error while running tests

### ISSUE THREAD

**Issue by iamsimha** [dlsyscourse/hw3#3]
Steps to reproduce:

` !python3 -m pytest -v -k "(permute or reshape or broadcast or getitem) and cpu and not compact"
`

Traceback:
../../../opt/anaconda3/envs/dlsys/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_ndarray.py:6: in <module>
    import needle as ndl
python/needle/__init__.py:1: in <module>
    from . import ops
python/needle/ops.py:5: in <module>
    from .autograd import NDArray
python/needle/autograd.py:12: in <module>
    from .backend_selection import Device, array_api, NDArray, default_device
python/needle/backend_selection.py:9: in <module>
    from . import backend_ndarray as array_api
python/needle/backend_ndarray/__init__.py:1: in <module>
    from .ndarray import *
python/needle/backend_ndarray/ndarray.py:6: in <module>
    from . import ndarray_backend_cpu
E   ImportError: cannot import name 'ndarray_backend_cpu' from partially initialized module 'needle.backend_ndarray' (most likely due to a circular import) (/Users/talurj/Documents/dlsys/hw3/python/needle/backend_ndarray/__init__.py)

**Comment by iamsimha** [comment]
You need to run make  :upside_down_face:

**Comment by shenghansen** [comment]
hi I met same problem as you,could you please tell me how to fix it?
I make before test,but it does not work

**Comment by lordidiot** [comment]
Had this issue too, went away when I stopped using my `conda` environment. Not sure what about `conda` messed it up but using venv instead fixed this.
